### ISSUE TITLE
KeyError when running manager.reduce_scope() in example notebook

### ISSUE THREAD

**Issue by snkeegan** [VIDA-NYU/bdi-kit#40] opened 2024-05-30 15:56 UTC
When I run the cell with the code "manager.reduce_scope()" in the column_and_value_mapping notebook from the examples, I get the following error.  I can see the histogram and table printed but then the error occurs.

Cache directory does not exist, creating it at: /gpfs/home/snk218/.cache/bdikit/models
Downloading model cl-reducer-v0.1 from Box to /gpfs/home/snk218/.cache/bdikit/models/cl-reducer-v0.1
100%
 501M/501M [00:05<00:00, 92.7MB/s]
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|          | 0/17 [00:00<?, ?it/s]We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.
100%|██████████| 17/17 [00:00<00:00, 23.39it/s]
Table features extracted from 17 columns
100%|██████████| 734/734 [00:32<00:00, 22.92it/s]
Table features extracted from 734 columns
Traceback (most recent call last):
Traceback (most recent call last):
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/models/comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
KeyError: 'content'
Traceback (most recent call last):
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/models/comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
KeyError: 'content'
Traceback (most recent call last):
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/models/comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
KeyError: 'content'
Traceback (most recent call last):
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/models/comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
KeyError: 'content'
Traceback (most recent call last):
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/models/comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
KeyError: 'content'
Traceback (most recent call last):
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/models/comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
KeyError: 'content'
Traceback (most recent call last):
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
  File "/gpfs/data/proteomics/home/snk218/software/miniforge3/envs/py310/lib/python3.10/site-packages/panel/models/comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
KeyError: 'content'

**Comment by aecio** [comment] 2024-05-30 18:54
This is looking like an error in the dependencies, probably some incompatible version was installed in your environment. What version of `panel` do you get when you run `pip show panel`?

**Comment by roquelopez** [comment] 2024-05-30 18:55
@viguardieiro could you please check this problem? It seems an issue with the version of `panel`.

**Comment by viguardieiro** [comment] 2024-05-30 19:15
> @viguardieiro could you please check this problem? It seems an issue with the version of `panel`.

@EdenWuyifan is having this exact error when running in NYU HPC. We still don't know the cause, but it doesn't seem to be related to `panel`'s version.

**Comment by EdenWuyifan** [comment] 2024-06-03 19:47
I have met this issue before @snkeegan , here's the ticket from Panel: https://github.com/holoviz/panel/issues/6865

They said to fix this with version 1.4.4, I will take a look and try to fix this.

**Comment by aecio** [comment] 2024-07-08 14:28
@EdenWuyifan  So the fix is just to add `panel != 1.4.3` in the requirements? Can you submit a PR so we can close this issue?

**Comment by aecio** [comment] 2024-07-09 02:42
Fixed in commit 38b2b00.

**Closed by aecio** 2024-07-09 02:42 UTC
Labels: bug
